<?php

namespace Database\Seeders;

use App\Models\Content;
use Illuminate\Database\Seeder;

class ContentSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $contents = array(
      array('id' => '1', 'locale' => 'ru', 'slug' => 'main-page-board-ru', 'page' => 'main', 'content' => '<h1>Группа компаний</h1><h1>КОИНОТИ НАВ</h1><p>ВЕРИМ, МОЖЕМ, СОЗДАЕМ<br></p><p><a href="/about/history" target="_self">Подробнее</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:05:53'),
      array('id' => '3', 'locale' => 'ru', 'slug' => 'main-page-management-ru', 'page' => 'main', 'content' => '<h2>Наш менеджмент</h2><p>В нас сочетаются инновации и традиции.</p><p>Мы знак истинного качества, символ верности</p><p>и преданности своему делу, своему обществу и стране.</p><p><a href="/about/management" target="_self">Подробнее</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:14:18'),
      array('id' => '5', 'locale' => 'ru', 'slug' => 'main-page-investors-ru', 'page' => 'main', 'content' => '<h2>Инвесторам<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.</p><p><a href="/partnership/investors" target="_self">Подробнее</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:19:07'),
      array('id' => '7', 'locale' => 'ru', 'slug' => 'main-page-contribution-ru', 'page' => 'main', 'content' => '<h2>Вклад в общество<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.</p><p><a href="/contribution" target="_self">Подробнее</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:35:32'),
      array('id' => '9', 'locale' => 'ru', 'slug' => 'main-page-opportunity-ru', 'page' => 'main', 'content' => '<h2>Страна </h2><h2>возможностей</h2><p>Современный Таджикистан</p><p><a href="/" target="_self">Смотреть видео</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:38:04'),
      array('id' => '11', 'locale' => 'ru', 'slug' => 'main-page-news-ru', 'page' => 'main', 'content' => '<h2>Наши новости<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed</p><p>ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed</p><p>aliquam sed ullamcorper.<br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:28:57'),
      array('id' => '13', 'locale' => 'ru', 'slug' => 'main-page-projects-ru', 'page' => 'main', 'content' => '<h2>Наши проекты<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed</p><p>ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed</p><p>aliquam sed ullamcorper.<br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:29:39'),
      array('id' => '15', 'locale' => 'ru', 'slug' => 'history-page-board-ru', 'page' => 'about.history', 'content' => '<h1>Группа компаний</h1><h1>КОИНОТИ НАВ</h1><p>ВЕРИМ, МОЖЕМ, СОЗДАЕМ<br></p><p style="margin-left: 240px;"><a href="/about/history" target="_self">Смотреть видео</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:38:36'),
      array('id' => '17', 'locale' => 'ru', 'slug' => 'history-page-content-ru', 'page' => 'about.history', 'content' => '<h2>О нас<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:39:16'),
      array('id' => '19', 'locale' => 'ru', 'slug' => 'management-page-board-ru', 'page' => 'about.management', 'content' => '<h1>Наша</h1><h1>команда</h1><p>Верим, можем, создаем<br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:59:57'),
      array('id' => '21', 'locale' => 'ru', 'slug' => 'management-page-specialists-ru', 'page' => 'about.management', 'content' => '<h2>Lorem Ipsum</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:01:21'),
      array('id' => '23', 'locale' => 'ru', 'slug' => 'mission-page-board-ru', 'page' => 'about.mission', 'content' => '<h1>Наша миссия<br></h1><p>Способствовать общественному</p><p>благополучию</p><p><a href="/about/mission" target="_self">Смотреть видео</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:45:03'),
      array('id' => '25', 'locale' => 'ru', 'slug' => 'mission-page-mission-ru', 'page' => 'about.mission', 'content' => '<h2>Lorem Ipsum<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam&nbsp;</p><p>pellentesque facilisis egestas risus egestas sit gravida.<br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:47:11'),
      array('id' => '27', 'locale' => 'ru', 'slug' => 'mission-page-vision-board-ru', 'page' => 'about.mission', 'content' => '<h2>Наше видение</h2><p>Развиваясь инновационно и динамично</p><p>занять лидирующее положение в сферах деятельности</p><p><a href="/about/mission" target="_self">Смотреть видео</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:50:48'),
      array('id' => '29', 'locale' => 'ru', 'slug' => 'mission-page-vision-ru', 'page' => 'about.mission', 'content' => '<h2>Lorem Ipsum<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam&nbsp;</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:47:27'),
      array('id' => '31', 'locale' => 'ru', 'slug' => 'mission-page-values-board-ru', 'page' => 'about.mission', 'content' => '<h2>Наши ценности<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p><p>Dignissim aliquam pellentesque facilisis egestas risus</p><p>egestas sit gravida.</p><p><a href="/about/mission" target="_self">Смотреть видео</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:53:19'),
      array('id' => '33', 'locale' => 'ru', 'slug' => 'mission-page-value-1-ru', 'page' => 'about.mission', 'content' => '<h3>Уважение<br></h3><p>Мы признаем ценность каждого человека в компании, уважаем его труд, время, свободу и собственное мнение.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:54:31'),
      array('id' => '35', 'locale' => 'ru', 'slug' => 'mission-page-value-2-ru', 'page' => 'about.mission', 'content' => '<h3>Самореализация<br></h3><p>Мы создали внутри Компании атмосферу, способствующую самореализации каждого члена команды.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:54:52'),
      array('id' => '37', 'locale' => 'ru', 'slug' => 'mission-page-value-3-ru', 'page' => 'about.mission', 'content' => '<h3>Жизнерадостность<br></h3><p>Мы оптимистичны, жизнерадостны, заряжаем энергией позитива. Мы знаем, что имеем полное право радовать.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:55:18'),
      array('id' => '39', 'locale' => 'ru', 'slug' => 'mission-page-value-4-ru', 'page' => 'about.mission', 'content' => '<h3>Здоровье<br></h3><p>Здоровье – это главная ценность жизни. Здоровье – это состояние полного физического и социального благополучия.<br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:55:46'),
      array('id' => '41', 'locale' => 'ru', 'slug' => 'mission-page-value-5-ru', 'page' => 'about.mission', 'content' => '<h3>Командность<br></h3><p>Наша сила в единстве и сплоченности, в осознанном предпочтении командных интересов.<br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:56:22'),
      array('id' => '43', 'locale' => 'ru', 'slug' => 'mission-page-value-6-ru', 'page' => 'about.mission', 'content' => '<h3>Профессионализм<br></h3><p>Мы постоянно работаем над повышением своего профессионального мастерства, совершенствуя знания и умения.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:56:43'),
      array('id' => '45', 'locale' => 'ru', 'slug' => 'mission-page-values-ru', 'page' => 'about.mission', 'content' => '<h2>Lorem Ipsum<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam&nbsp;</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 10:47:32'),
      array('id' => '47', 'locale' => 'ru', 'slug' => 'news-page-board-ru', 'page' => 'news', 'content' => '<h1>Новости<br></h1><p>Lorem ipsum dolor sit amet,</p><p>consectetur adipiscing elit.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:03:31'),
      array('id' => '49', 'locale' => 'ru', 'slug' => 'news-page-content-ru', 'page' => 'news', 'content' => '<h2>Lorem Ipsum</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:04:17'),
      array('id' => '51', 'locale' => 'ru', 'slug' => 'news-show-page-ru', 'page' => 'news.show', 'content' => '<h2>Lorem Ipsum</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:04:46'),
      array('id' => '53', 'locale' => 'ru', 'slug' => 'projects-page-board-ru', 'page' => 'projects', 'content' => '<h1>Наши проекты<br></h1><p>Lorem ipsum dolor sit amet,</p><p>consectetur adipiscing elit.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:10:34'),
      array('id' => '55', 'locale' => 'ru', 'slug' => 'projects-by-us-page-board-ru', 'page' => 'projects.by-us', 'content' => '<h1>Наши проекты<br></h1><p>Lorem ipsum dolor sit amet,</p><p>consectetur adipiscing elit.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:12:15'),
      array('id' => '57', 'locale' => 'ru', 'slug' => 'projects-with-us-page-board-ru', 'page' => 'projects.with-us', 'content' => '<h1>Наши проекты<br></h1><p>Lorem ipsum dolor sit amet,</p><p>consectetur adipiscing elit.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:12:45'),
      array('id' => '59', 'locale' => 'ru', 'slug' => 'projects-page-ru', 'page' => 'projects', 'content' => '<h2>Lorem Ipsum</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:11:39'),
      array('id' => '61', 'locale' => 'ru', 'slug' => 'projects-by-us-page-ru', 'page' => 'projects.by-us', 'content' => '<h2>Lorem Ipsum</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:12:31'),
      array('id' => '63', 'locale' => 'ru', 'slug' => 'projects-with-us-page-ru', 'page' => 'projects.with-us', 'content' => '<h2>Lorem Ipsum</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:12:58'),
      array('id' => '65', 'locale' => 'ru', 'slug' => 'investors-page-board-ru', 'page' => 'partnership.investors', 'content' => '<h1>Страна </h1><h1>возможностей</h1><p>Современный Таджикистан<br></p><p style="margin-left: 200px;"><a href="/partnership/investors" target="_self">Смотреть видео</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:16:53'),
      array('id' => '67', 'locale' => 'ru', 'slug' => 'investors-page-about-ru', 'page' => 'partnership.investors', 'content' => '<h2>О Таджикистане<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:17:21'),
      array('id' => '69', 'locale' => 'ru', 'slug' => 'investors-page-connection-ru', 'page' => 'partnership.investors', 'content' => '<h2>Связь с нами<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.<a href="/projects" target="_self">Наши проекты</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:18:28'),
      array('id' => '71', 'locale' => 'ru', 'slug' => 'startups-page-board-ru', 'page' => 'partnership.startups', 'content' => '<h1>Наше видение<br></h1><p>Развиваясь инновационно и динамично</p><p>занять лидирующее положение в сферах деятельности</p><p style="margin-left: 560px;"><a href="/partnership/startups" target="_self">Смотреть видео</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:21:10'),
      array('id' => '73', 'locale' => 'ru', 'slug' => 'startups-page-ru', 'page' => 'partnership.startups', 'content' => '<h2>Lorem Ipsum<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Habitant condimentum aenean mauris, lacinia pharetra consequat, pharetra. Lectus venenatis, facilisi sed augue massa odio integer viverra a. Libero ut et, egestas felis. Duis penatibus eu, dictumst viverra eu, pharetra nam id. Rhoncus praesent ac sed leo a dolor. Et, nunc vulputate tortor in. Nunc tellus blandit nam eget cras. Ac aliquet phasellus rhoncus, dolor.</p><p>Venenatis, odio sed lectus porta vitae nec bibendum. Tincidunt enim est, enim, nulla eget gravida. At egestas amet, lorem purus non. Amet nam duis diam fermentum lorem dignissim. Ullamcorper in donec nulla&nbsp;</p><p>dignissim pretium sed aliquam.</p><p><br></p><p>Justo est odio sed faucibus commodo in. Risus lectus ipsum orci, duis ante sapien, amet libero, tellus. At ac lobortis arcu, diam. Lacus eu purus ultricies sed gravida lectus eget. Sed ipsum, tellus euismod condimentum. Nulla hendrerit tempor elementum eros elementum rhoncus tempor. Lectus amet urna turpis euismod nec velit fringilla vitae nulla. Egestas id cursus sollicitudin arcu, quis venenatis sit cursus. Laoreet interdum eu augue egestas viverra aliquet. Natoque sapien, elementum lobortis elementum. Amet, diam quisque nullam consectetur nibh nec egestas. Tempus sem tellus elit placerat enim. Integer faucibus sed convallis neque, pretium, eu.</p><p><br></p><p>Orci risus blandit in duis sagittis ipsum nulla massa nisl. Nisi, aliquet in gravida leo, amet fermentum. Convallis fermentum, fermentum aliquet nisl nisl semper purus tempor amet. Vestibulum vitae, nunc, ipsum, sed et orci cum at tellus. Interdum aliquam interdum tristique cras vel eros, dignissim sed tincidunt. Gravida vitae velit metus sem sed ut odio sed volutpat. Risus leo aliquam aliquam donec iaculis. Volutpat cras tellus nunc nisi sit blandit cursus aliquam nunc. Tristique varius fermentum adipiscing diam id integer molestie ipsum. Morbi nunc pretium sed tempor urna elementum. Sit gravida consectetur eu arcu. Eu, nisl, nec nulla tincidunt.</p><p><br></p><p>Nam nunc, habitant leo risus tortor mi imperdiet. Condimentum cursus velit egestas proin erat enim quis proin est.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:22:25'),
      array('id' => '75', 'locale' => 'ru', 'slug' => 'startups-page-form-ru', 'page' => 'partnership.startups', 'content' => '<h2>Форма обратной связи<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed aliquam sed <br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:23:02'),
      array('id' => '77', 'locale' => 'ru', 'slug' => 'startups-page-connection-ru', 'page' => 'partnership.startups', 'content' => '<h2>Связь с нами<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:27:07'),
      array('id' => '79', 'locale' => 'ru', 'slug' => 'contribution-page-board-ru', 'page' => 'contribution', 'content' => '<h1>Вклад в общество</h1><p>Lorem ipsum dolor sit amet,</p><p>consectetur adipiscing elit.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:30:48'),
      array('id' => '81', 'locale' => 'ru', 'slug' => 'contribution-page-ru', 'page' => 'contribution', 'content' => '<h2>Lorem Ipsum</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:31:01'),
      array('id' => '83', 'locale' => 'ru', 'slug' => 'contribution-show-page-ru', 'page' => 'contribution.show', 'content' => '<h2>Lorem Ipsum</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:31:24'),
      array('id' => '85', 'locale' => 'ru', 'slug' => 'contacts-page-office-ru', 'page' => 'contacts', 'content' => '<h2>Связь с нами<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:32:56'),
      array('id' => '87', 'locale' => 'ru', 'slug' => 'contacts-page-connection-ru', 'page' => 'contacts', 'content' => '', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 09:50:52'),
      array('id' => '89', 'locale' => 'ru', 'slug' => 'carrier-page-board-ru', 'page' => 'carrier', 'content' => '<h2>Общекомандная цель<br></h2><p>Создать инновационную и динамично</p><p>развивающуюся команду</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:35:38'),
      array('id' => '91', 'locale' => 'ru', 'slug' => 'carrier-page-formula-ru', 'page' => 'carrier', 'content' => '<h2>Наша формула успеха<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:36:03'),
      array('id' => '93', 'locale' => 'ru', 'slug' => 'carrier-page-principles-ru', 'page' => 'carrier', 'content' => '<h2>Наши принципы<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare vitae sed</p><p>aliquam sed ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing</p><p>elit. Ornare vitae sed aliquam sed ullamcorper.<br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:36:42'),
      array('id' => '95', 'locale' => 'ru', 'slug' => 'carrier-page-internship-ru', 'page' => 'carrier', 'content' => '<h2>Стажировка<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Habitant condimentum aenean mauris, lacinia pharetra consequat, pharetra. Lectus venenatis, facilisi sed augue massa odio integer viverra a. Libero ut et, egestas felis. Duis penatibus eu, dictumst viverra eu, pharetra nam id. Rhoncus praesent ac sed leo a dolor. Et, nunc vulputate tortor in. Nunc tellus blandit nam eget cras. Ac aliquet phasellus rhoncus, dolor.</p><p><br></p><p>Venenatis, odio sed lectus porta vitae nec bibendum. Tincidunt enim est, enim, nulla eget gravida. At egestas amet, lorem purus non. Amet nam duis diam fermentum lorem dignissim. Ullamcorper in donec nulla dignissim pretium sed aliquam.</p><p><a href="/carrier/test" target="_self">Пройдите тестирование</a></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:37:53'),
      array('id' => '97', 'locale' => 'ru', 'slug' => 'test-page-board-ru', 'page' => 'carrier.test', 'content' => '<h1>Lorem Ipsum<br></h1><p>Lorem ipsum dolor sit amet,</p><p>consectetur adipiscing elit.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:40:14'),
      array('id' => '99', 'locale' => 'ru', 'slug' => 'test-page-stages-ru', 'page' => 'carrier.test', 'content' => '<h2>Карьерные этапы<br></h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:40:49'),
      array('id' => '101', 'locale' => 'ru', 'slug' => 'test-page-test-ru', 'page' => 'carrier.test', 'content' => '<h2>Lorem Ipsum</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim aliquam</p><p>pellentesque facilisis egestas risus egestas sit gravida.</p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:41:12'),
      array('id' => '103', 'locale' => 'ru', 'slug' => 'test-page-form-ru', 'page' => 'carrier.test', 'content' => '<h2>Пройди тест и стань</h2><h2>частью нашей команды</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ornare</p><p>vitae sed aliquam sed ullamcorper.Lorem ipsum dolor sit amet,</p><p>consectetur adipiscing elit. Ornare vitae sed aliquam sed<br></p>', 'created_at' => '2022-07-29 09:50:52', 'updated_at' => '2022-07-29 11:45:29'),
    );

    foreach ($contents as $content) {
      Content::create([
        'locale' => 'ru',
        'slug' => $content['slug'],
        'page' => $content['page'],
        'content' => $content['content'],
      ]);

      Content::create([
        'locale' => 'en',
        'slug' => substr($content['slug'], 0, -2) . 'en',
        'page' => $content['page'],
        'content' => $content['content'],
      ]);
    }
  }
}
